# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [1]:
import numpy as np

all_data = np.loadtxt('data/minutes_n_ingredients.csv', skiprows=1, delimiter=',', dtype=np.int32)
print(all_data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [2]:
cols = [1, 2]
average_val = np.mean(all_data[:, cols], axis = 0, dtype = np.int32)
min_val = np.amin(all_data[:, cols], axis=0)
max_val = np.amax(all_data[:, cols], axis=0)
median_val = np.median(all_data[:, cols], axis=0)
print(f'Средние значения: {average_val}')
print(f'Минимальные значения: {min_val}')
print(f'Максимальные значения: {max_val}')
print(f'Медианы: {median_val}')

Средние значения: [-21348      9]
Минимальные значения: [0 1]
Максимальные значения: [2147483647         39]
Медианы: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [3]:
quan = np.quantile(all_data[:, 1], 0.75)
all_data[:, 1] = all_data[:, 1].clip(max=quan)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [4]:
value = all_data[:, 1].size - np.count_nonzero(all_data[:, 1])
print(f'Количество рецептов равных 0: {value}')
all_data[:, 1][all_data[:, 1] == 0 ] = 1
value = all_data[:, 1].size - np.count_nonzero(all_data[:, 1])
print(f'Проверка: {value}')

Количество рецептов равных 0: 479
Проверка: 0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [5]:
count = len(np.unique(all_data[:, 0]))
print(f'Количество уникальных рецептов: {count}')

Количество уникальных рецептов: 100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [6]:
count = len(np.unique(all_data[:, 2]))
unique = np.unique(all_data[:, 2])
print(f'Количество различных значений кол-ва ингредиентов: {count}')
print(f'Различные значения кол-ва ингредиентов: {unique}')

Количество различных значений кол-ва ингредиентов: 37
Различные значения кол-ва ингредиентов: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [7]:
index = np.where(all_data[:, 2] > 5 )
np.delete(all_data, index, 0)

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [8]:
minutes = all_data[:, 1]
ingredients = all_data[:, 2]

one = ingredients / minutes
print(np.amax(one))

24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [9]:
x_sorted_desc = all_data[all_data[:, 1]. argsort ()[::-1]]
hundred = x_sorted_desc[:100]
last = hundred[:, 2]
print(f'Среднее: {np.mean(last)}')

Среднее: 9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [10]:
rows, columns = all_data.shape
cols = [np.random.randint(0, rows+1) for i in range(10)]
print(all_data[cols, :])

[[168785     35      9]
 [183413      6      8]
 [396133     25      5]
 [309969      5      6]
 [150204     25      8]
 [403594     65      7]
 [105350     35     12]
 [191234     25     10]
 [263988      5      4]
 [277495      2      4]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [11]:
average = np.mean(ingredients)
num = ingredients < average
final = ingredients[num].size * 100 / ingredients.size
print(f'{final}%')

58.802%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [12]:
rows, columns = all_data.shape
onesArr = np.zeros((rows, 1), dtype=np.int32)
all_data_1 = np.concatenate((all_data, onesArr), axis=1)
indexes = np.where((ingredients <= 5) & (minutes <= 20))
all_data_1[indexes, 3] = 1
print(all_data_1)


[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [13]:
column = all_data_1[:, 3]
num = column == 1
final = column[num].size * 100 / column.size
print(f'{final}%')

9.552%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [14]:
first = all_data[all_data[:, 1] < 10]
second = all_data[(all_data[:, 1] >= 10) & (all_data[:, 1] < 20)]
third = all_data[all_data[:, 1] > 20]
max = min(map(len, [first, second, third]))
final = np.vstack(([first[:max,:]], [second[:max,:]], [third[:max,:]]))
print(final.shape)

(3, 7588, 3)
